# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "app-test3"
client_id = "9ad19c13edaaefca3b90d6120b66d7d9"
application_url = "https://per-fight-consistently-examines.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://per-fight-consistently-examines.trycloudflare.com/auth/callback",
  "https://per-fight-consistently-examines.trycloudflare.com/auth/shopify/callback",
  "https://per-fight-consistently-examines.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xn-zckzah7003aj75b.myshopify.com"
